
export { default as Settings        } from './Settings'
export { default as AppSettings     } from './AppSettings'
export { default as HomeSettings    } from './HomesSettings'
export { default as About           } from './About'
export { default as Tos             } from './ToS'
export { default as Licenses        } from './Licenses'
export { default as License         } from './License'
export { default as SystemsSettings } from './SystemsSettings'
export { default as AccountSettings } from './AccountSettings'
